const mockCarData = [
  {
    carId: 1,
    make: 'BMW',
    model: 'M8',
    year: 2024,
    condition: 'NEW',
    price: 100000,
    maxPrice: 120000,
    installmentTerm: 60,
    interestRate: 5.5,
    downPayment: 20000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
    images: {
      image1: '/src/mock/car.png',
      image2: '/src/mock/car1.png',
      image3: '/src/mock/car2.png',
      image4: '/src/mock/car3.png',
    },
  },
  {
    carId: 2,
    make: 'Audi',
    model: 'A6',
    year: 2023,
    condition: 'NEW',
    price: 75000,
    maxPrice: 90000,
    installmentTerm: 48,
    interestRate: 4.2,
    downPayment: 15000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
  },
  {
    carId: 3,
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2022,
    condition: 'USED',
    price: 60000,
    maxPrice: 80000,
    installmentTerm: 36,
    interestRate: 3.8,
    downPayment: 12000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
  },
  {
    carId: 4,
    make: 'Toyota',
    model: 'Camry',
    year: 2021,
    condition: 'USED',
    price: 30000,
    maxPrice: 35000,
    installmentTerm: 24,
    interestRate: 3.5,
    downPayment: 5000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
  },
  {
    carId: 5,
    make: 'Tesla',
    model: 'Model S',
    year: 2023,
    condition: 'NEW',
    price: 95000,
    maxPrice: 110000,
    installmentTerm: 60,
    interestRate: 5.0,
    downPayment: 20000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
  },
  {
    carId: 6,
    make: 'Ford',
    model: 'Mustang',
    year: 2020,
    condition: 'USED',
    price: 45000,
    maxPrice: 55000,
    installmentTerm: 36,
    interestRate: 4.0,
    downPayment: 8000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
  },
  {
    carId: 7,
    make: 'Chevrolet',
    model: 'Corvette',
    year: 2024,
    condition: 'NEW',
    price: 85000,
    maxPrice: 100000,
    installmentTerm: 48,
    interestRate: 4.8,
    downPayment: 15000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
  },
  {
    carId: 8,
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    condition: 'USED',
    price: 22000,
    maxPrice: 25000,
    installmentTerm: 24,
    interestRate: 3.2,
    downPayment: 4000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
  },
  {
    carId: 9,
    make: 'Lexus',
    model: 'RX',
    year: 2023,
    condition: 'NEW',
    price: 60000,
    maxPrice: 75000,
    installmentTerm: 36,
    interestRate: 4.5,
    downPayment: 10000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
  },
  {
    carId: 10,
    make: 'Porsche',
    model: '911',
    year: 2024,
    condition: 'NEW',
    price: 120000,
    maxPrice: 150000,
    installmentTerm: 60,
    interestRate: 5.8,
    downPayment: 25000,
    shortDescription: 'SHORT DESCRIPTION WILL BE DISPLAYED HERE 123',
  },
];

export default mockCarData;
