export const carBrands = [
  { index: 0, label: 'Acura', model: ['Cecuta', 'Vios'] },
  { index: 1, label: 'Alfa Romeo', model: ['Giulia', 'Stelvio', '4C Spider'] },
  { index: 2, label: 'Asia', model: ['Asia 800', 'Asia 1000'] },
  { index: 3, label: 'Aston Martin', model: ['DB11', 'Vantage', 'DBX'] },
  { index: 4, label: 'Audi', model: ['A3', 'A4', 'Q5', 'Q7', 'R8'] },
  { index: 5, label: 'Baic', model: ['BJ40', 'X35', 'E160'] },
  { index: 6, label: 'Bentley', model: ['Continental GT', 'Flying Spur', 'Bentayga'] },
  { index: 7, label: 'BMW', model: ['3 Series', '5 Series', 'X3', 'X5', 'Z4', 'i8'] },
  { index: 8, label: 'Buick', model: ['Enclave', 'Encore', 'LaCrosse'] },
  { index: 9, label: 'BYD', model: ['Tang', 'Song', 'F3', 'Yuan EV'] },
  { index: 10, label: 'Cadillac', model: ['Escalade', 'XT5', 'CT6', 'ATS'] },
  { index: 11, label: 'Changan', model: ['CS75', 'Eado', 'Alsvin'] },
  { index: 12, label: 'Chery', model: ['Tiggo 2', 'Arrizo 5', 'EQ1'] },
  { index: 13, label: 'Chevrolet', model: ['Cruze', 'Malibu', 'Equinox', 'Tahoe', 'Silverado'] },
  { index: 14, label: 'Chrysler', model: ['Pacifica', 'Voyager', '300'] },
  { index: 15, label: 'Citroen', model: ['C3', 'C4', 'Berlingo'] },
  { index: 16, label: 'Daewoo', model: ['Matiz', 'Lacetti', 'Nubira'] },
  { index: 17, label: 'Daihatsu', model: ['Terios', 'Sirion', 'Xenia'] },
  { index: 18, label: 'Dodge', model: ['Charger', 'Durango', 'Ram 1500'] },
  { index: 19, label: 'Ferrari', model: ['488 GTB', 'Portofino', 'LaFerrari'] },
  { index: 20, label: 'Fiat', model: ['500', 'Panda', 'Tipo'] },
  { index: 21, label: 'Ford', model: ['Fiesta', 'Focus', 'Mustang', 'Escape', 'Explorer', 'F-150'] },
  { index: 22, label: 'GAC', model: ['GS8', 'GS5', 'GA6'] },
  { index: 23, label: 'Gaz', model: ['Gazelle', 'Volga', 'Sable'] },
  { index: 24, label: 'Geely', model: ['Emgrand', 'Binyue', 'Bo Yue'] },
  { index: 25, label: 'Genesis', model: ['G70', 'G80', 'G90'] },
  { index: 26, label: 'GMC', model: ['Sierra', 'Canyon', 'Yukon'] },
  { index: 27, label: 'Haima', model: ['S5', 'Haima 7', 'Haima 8'] },
  { index: 28, label: 'Haval', model: ['H6', 'H9', 'F7'] },
  { index: 29, label: 'Honda', model: ['Civic', 'Accord', 'CR-V', 'Pilot', 'Ridgeline'] },
  { index: 30, label: 'HongQi', model: ['H9', 'L5', 'E-HS9'] },
  { index: 31, label: 'Hummer', model: ['H2', 'H3', 'EV'] },
  { index: 32, label: 'Hyundai', model: ['Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Kona'] },
  { index: 33, label: 'Infiniti', model: ['Q50', 'QX60', 'QX80'] },
  { index: 34, label: 'Isuzu', model: ['D-Max', 'MU-X', 'V-Cross'] },
  { index: 35, label: 'Jaguar', model: ['XE', 'F-Type', 'XF', 'E-PACE'] },
  { index: 36, label: 'Jeep', model: ['Cherokee', 'Grand Cherokee', 'Wrangler'] },
  { index: 37, label: 'Kia', model: ['Optima', 'Seltos', 'Sportage', 'Sorento', 'Carnival'] },
  { index: 38, label: 'Lada', model: ['Niva', 'Granta', 'Vesta'] },
  { index: 39, label: 'Lamborghini', model: ['Aventador', 'Huracan', 'Urus'] },
  { index: 40, label: 'LandRover', model: ['Defender', 'Discovery', 'Range Rover'] },
  { index: 41, label: 'Lexus', model: ['RX', 'NX', 'IS', 'LS', 'UX'] },
  { index: 42, label: 'Lifan', model: ['X60', 'X80', 'Lifan 520'] },
  { index: 43, label: 'Lincoln', model: ['Nautilus', 'Aviator', 'Continental'] },
  { index: 44, label: 'Luxgen', model: ['Luxgen 7', 'U6 Turbo', 'S5 Turbo'] },
  { index: 45, label: 'Lynk&Co', model: ['01', '02', '03'] },
  { index: 46, label: 'Man', model: ['TGE', 'Lions City'] },
  { index: 47, label: 'Maserati', model: ['Ghibli', 'Quattroporte', 'Levante'] },
  { index: 48, label: 'Maybach', model: ['S-Class', 'Mercedes-Maybach GLS'] },
  { index: 49, label: 'Mazda', model: ['CX-5', 'Mazda 3', 'Mazda 6'] },
  { index: 50, label: 'Mekong', model: ['Mekong X5', 'Mekong X3'] },
  { index: 51, label: 'Mercedes Benz', model: ['C-Class', 'S-Class', 'E-Class', 'GLA', 'GLC'] },
  { index: 52, label: 'Mercury', model: ['Grand Marquis', 'Milan', 'Sable'] },
  { index: 53, label: 'MG', model: ['MG ZS', 'MG Hector', 'MG6'] },
  { index: 54, label: 'Mini', model: ['Cooper', 'Clubman', 'Countryman'] },
  { index: 55, label: 'Mitsubishi', model: ['Outlander', 'Pajero', 'Lancer'] },
  { index: 56, label: 'Nissan', model: ['Altima', 'Maxima', 'Rogue', 'Murano', 'Titan'] },
  { index: 57, label: 'Opel', model: ['Astra', 'Insignia', 'Corsa'] },
  { index: 58, label: 'Peugeot', model: ['208', '3008', '508'] },
  { index: 59, label: 'Pontiac', model: ['G6', 'Bonneville', 'Grand Prix'] },
  { index: 60, label: 'Porsche', model: ['911', 'Cayenne', 'Macan', 'Panamera'] },
  { index: 61, label: 'Proton', model: ['Persona', 'Iriz', 'X70'] },
  { index: 62, label: 'RAM', model: ['1500', '2500', '3500'] },
  { index: 63, label: 'Renault', model: ['Clio', 'Megane', 'Captur'] },
  { index: 64, label: 'Reult', model: [] },
  { index: 65, label: 'Rolls Royce', model: ['Phantom', 'Ghost', 'Cullinan'] },
  { index: 66, label: 'Rover', model: ['Land Rover', 'Range Rover'] },
  { index: 67, label: 'Samsung', model: ['SM3', 'SM5'] },
  { index: 68, label: 'Scion', model: ['tC', 'xB', 'iA'] },
  { index: 69, label: 'Skoda', model: ['Octavia', 'Superb', 'Kodiaq'] },
  { index: 70, label: 'Smart', model: ['ForTwo', 'ForFour'] },
  { index: 71, label: 'Ssangyong', model: ['Tivoli', 'Korando', 'Rexton'] },
  { index: 72, label: 'Subaru', model: ['Forester', 'Outback', 'Impreza'] },
  { index: 73, label: 'Suzuki', model: ['Swift', 'Vitara', 'S-Cross'] },
  { index: 74, label: 'SYM', model: [] },
  { index: 75, label: 'Tesla', model: ['Model S', 'Model 3', 'Model X', 'Model Y'] },
  { index: 76, label: 'Toyota', model: ['Corolla', 'Camry', 'RAV4', 'Highlander', 'Tacoma'] },
  { index: 77, label: 'UAZ', model: ['Patriot', 'Hunter'] },
  { index: 78, label: 'VinFast', model: ['VF8', 'VF9'] },
  { index: 79, label: 'Volkswagen', model: ['Golf', 'Passat', 'Tiguan', 'Atlas', 'Beetle'] },
  { index: 80, label: 'Volvo', model: ['XC40', 'XC60', 'XC90', 'S60', 'V90'] },
  { index: 81, label: 'Wuling', model: ['HongGuang', 'Almaz', 'Baojun 730'] },
  { index: 82, label: 'Zotye', model: ['Z100', 'T600', 'Z300'] },
  { index: 83, label: 'Hãng khác', model: [] },
];
